version: 1.0.{build}
image:
- Ubuntu1804
- Visual Studio 2017
environment:
  COVERALLS_SERVICE_NAME: appveyor
  COVERALLS_REPO_TOKEN:
    secure: StCrOCFf1u9vz1UjgNQp9iOzA3n1v6Ce9wA1517VokDb6SP0JgOpyNPWp2HkYwJQ
  matrix:
  - nodejs_version: 8
  - nodejs_version: 10
install:
- cmd: powershell Install-Product node $env:nodejs_version
- sh: nvm install $nodejs_version
- npm install
build_script:
- npm run build
test_script:
- node --version
- npm --version
- npm run coverage
cache:
- node_modules -> package.json
matrix:
  fast_finish: true
for:
-
  matrix:
    only:
      - image: Ubuntu1804
        nodejs_version: 10
  on_success:
  - npm run coveralls-upload
